<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Minyak Balur Keris Barokah',
                'category' => 'kesehatan',
                'description' => 'Racikan 99 tanaman obat asli Nusantara berkhasiat tinggi. Efektif meredakan pegal linu, masuk angin, kembung, serta memperlancar aliran energi tubuh.',
                'price' => 'Rp 85.000',
                'badge' => 'Terlaris',
                'rating' => 4.9,
                'image' => null,
                'icon' => 'fas fa-droplet',
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20memesan%20Minyak%20Balur%20Keris%20Barokah',
            ],
            [
                'name' => 'Alfachanna (Ekstrak Channa Strata)',
                'category' => 'kesehatan',
                'description' => 'Suplemen kesehatan premium ekstrak ikan Channa Strata (ikan gabus) murni kaya albumin & protein. Membantu mempercepat pemulihan luka pasca operasi, meningkatkan daya tahan tubuh, dan menjaga stamina tetap bugar.',
                'price' => 'Rp 250.000',
                'badge' => 'Rekomendasi',
                'rating' => 4.9,
                'image' => 'images/alfachanna.jpg',
                'icon' => null,
                'has_detail' => true,
                'detail_image' => 'images/alfachanna-brosur.jpg',
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20memesan%20Alfachanna%20Ekstrak%20Channa%20Strata',
            ],
            [
                'name' => 'eJEMmizu (Air Mineral Elektron Charge)',
                'category' => 'kesehatan',
                'description' => 'Air minum fungsional yang diperkaya elektron charge dan mineral alami berkualitas. Membantu menjaga metabolisme energi, perlindungan seluler, serta keseimbangan cairan tubuh.',
                'price' => 'Hubungi Kami',
                'badge' => 'Air Sehat',
                'rating' => 5.0,
                'image' => 'images/ejemmizu.jpg',
                'icon' => null,
                'has_detail' => true,
                'detail_image' => 'images/ejemmizu-brosur.jpg',
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20memesan%20Air%20Mineral%20eJEMmizu',
            ],
            [
                'name' => 'Susu Kambing Etawa Al Anwar',
                'category' => 'kesehatan',
                'description' => 'Campuran susu kambing Etawa dan krimer bubuk bernutrisi tinggi. Membantu menjaga kesehatan tulang, sendi, meredakan nyeri, mengontrol kolesterol, dan memelihara kesehatan tubuh.',
                'price' => 'Rp 50.000',
                'badge' => 'Nutrisi Tinggi',
                'rating' => 5.0,
                'image' => 'images/susu-al-anwar.jpg',
                'icon' => null,
                'has_detail' => true,
                'detail_image' => 'images/susu-al-anwar-brosur.png',
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20memesan%20Susu%20Kambing%20Etawa%20Al%20Anwar',
            ],
            [
                'name' => 'Set Alat Bekam Vakum Premium',
                'category' => 'terapi',
                'description' => 'Paket alat bekam higienis standar klinik kesehatan terpadu. Dilengkapi dengan pompa vakum anti-retak dan berbagai ukuran mangkok bekam praktis.',
                'price' => 'Rp 150.000',
                'badge' => 'Premium',
                'rating' => 4.8,
                'image' => null,
                'icon' => 'fas fa-kit-medical',
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20membeli%20Set%20Alat%20Bekam%20Vakum%20Premium',
            ],
            [
                'name' => 'Alfatron PEMF + Terahertz',
                'category' => 'terapi',
                'description' => 'Alat terapi kaki bio-resonansi modern dengan perpaduan teknologi PEMF dan gelombang Terahertz. Membantu melancarkan sirkulasi, memulihkan energi seluler, mendetoks tubuh, dan meredakan stress.',
                'price' => 'Rp 16.650.000',
                'badge' => 'Bio-Resonansi',
                'rating' => 5.0,
                'image' => 'images/terapi-pemf.jpg',
                'icon' => null,
                'has_detail' => true,
                'detail_image' => 'images/terapi-pemf-brosur.jpg',
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20dengan%20Alat%20Terapi%20Kaki%20PEMF%20%2B%20Terahertz%20Alfatron',
            ],
            [
                'name' => 'Serum Wajah Herbal Srikandi',
                'category' => 'skincare',
                'description' => 'Serum pencerah dan pelindung kulit dengan ekstrak teh hijau and bunga kantil. Teruji klinis melembapkan, menutrisi wajah, dan mencegah penuaan dini.',
                'price' => 'Rp 95.000',
                'badge' => 'BPOM',
                'rating' => 4.9,
                'image' => null,
                'icon' => 'fas fa-spa',
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20memesan%20Serum%20Wajah%20Herbal%20Srikandi',
            ],
            [
                'name' => 'Millagen (Supplement for Skin)',
                'category' => 'skincare',
                'description' => 'Suplemen nutrisi kulit premium perpaduan Etawa Goat Milk dan Fish Collagen murni. Membantu menjaga elastisitas, melembapkan, mencegah kerutan, serta merawat kecantikan kulit dari dalam.',
                'price' => 'Rp 200.000',
                'badge' => 'Collagen & Milk',
                'rating' => 5.0,
                'image' => 'images/millagen.jpg',
                'icon' => null,
                'has_detail' => true,
                'detail_image' => 'images/millagen-brosur.jpg',
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20memesan%20Millagen%20Supplement%20Skin',
            ],
            [
                'name' => 'Buku: Percakapan Bahasa Arab Amiyah',
                'category' => 'buku',
                'description' => 'Panduan praktis percakapan Bahasa Arab Amiyah (bahasa sehari-hari) yang dirancang khusus bagi calon jamaah haji, umroh, serta TKI di Arab Saudi. Memudahkan komunikasi selama berada di tanah suci.',
                'price' => 'Rp 145.000',
                'badge' => 'Best Seller',
                'rating' => 5.0,
                'image' => 'images/buku-bahasa-arab.jpg',
                'icon' => null,
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20untuk%20membeli%20Buku%20Panduan%20Percakapan%20Bahasa%20Arab%20Amiyah',
            ],
            [
                'name' => 'Paket Umroh Hemat SKB',
                'category' => 'travel',
                'description' => 'Hanya dengan Rp 2jt rupiah saja, Anda sudah bisa sampai di tanah suci! Dapatkan kemudahan keberangkatan ibadah Umroh dan Haji amanah dengan program tabungan syariah kami.',
                'price' => 'Rp 2 Jt (DP)',
                'badge' => 'Hemat & Berkah',
                'rating' => 5.0,
                'image' => null,
                'icon' => 'fas fa-kaaba',
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20dengan%20Paket%20Umroh%20Hemat%20cukup%202jt%20bisa%20berangkat',
            ],
            [
                'name' => 'Kavling Pandawangi Residence',
                'category' => 'properti',
                'description' => 'Tanah kavling matang siap bangun berlokasi strategis di Pandanwangi, Blimbing, Malang. Bebas banjir, sertifikat SHM bersih, dan dekat akses perkotaan.',
                'price' => 'Rp 185 Jt',
                'badge' => 'Strategis',
                'rating' => 4.7,
                'image' => null,
                'icon' => 'fas fa-house-chimney',
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20dengan%20info%20Kavling%20Pandawangi%20Residence',
            ],
            [
                'name' => 'Rumah Modern Srikandi Residence',
                'category' => 'properti',
                'description' => 'Hunian modern minimalis tipe 36/60 siap huni di wilayah Malang. Lingkungan asri dan aman, bebas banjir, sertifikat SHM dan IMB sudah siap tinggal balik nama.',
                'price' => 'Rp 295 Jt',
                'badge' => 'Siap Huni',
                'rating' => 4.8,
                'image' => null,
                'icon' => 'fas fa-building',
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20dengan%20info%20Rumah%20Modern%20Srikandi%20Residence',
            ],
            [
                'name' => 'Paket Pernikahan Lengkap Srikandi',
                'category' => 'wo',
                'description' => 'Solusi pernikahan impian Anda tanpa ribet! Paket lengkap mencakup penyewaan gedung, catering lezat, dekorasi pelaminan mewah, rias pengantin, MC, foto shoot dokumentasi, hingga mobil pengantin premium.',
                'price' => 'Mulai Rp 45 Jt',
                'badge' => 'Paket Lengkap',
                'rating' => 5.0,
                'image' => null,
                'icon' => 'fas fa-ring',
                'has_detail' => false,
                'detail_image' => null,
                'whatsapp_url' => 'https://wa.me/6285954572652?text=Halo%20CV.%20Srikandi%20Keris%20Barokah,%20saya%20tertarik%20dengan%20Paket%20Pernikahan%20Lengkap%20Wedding%20Organizer',
            ],
        ];

        foreach ($products as $prod) {
            Product::create($prod);
        }
    }
}
